var items = [{
    "first_name": "Willie",
    "last_name": "Jenkins",
    "favorite_color": "Maroon"
}, {
    "first_name": "Arthur",
    "last_name": "Nichols",
    "favorite_color": "Red"
}, {
    "first_name": "Johnny",
    "last_name": "Nelson",
    "favorite_color": "Puce"
}, {
    "first_name": "Annie",
    "last_name": "Brown",
    "favorite_color": "Mauv"
}, {
    "first_name": "Julie",
    "last_name": "Sullivan",
    "favorite_color": "Orange"
}, {
    "first_name": "Debra",
    "last_name": "Berry",
    "favorite_color": "Orange"
}, {
    "first_name": "Walter",
    "last_name": "Garza",
    "favorite_color": "Pink"
}, {
    "first_name": "Amanda",
    "last_name": "Barnes",
    "favorite_color": "Purple"
}, {
    "first_name": "Wanda",
    "last_name": "Dixon",
    "favorite_color": "Yellow"
}, {
    "first_name": "Rachel",
    "last_name": "Ford",
    "favorite_color": "Fuscia"
}, {
    "first_name": "Clarence",
    "last_name": "Lane",
    "favorite_color": "Orange"
}, {
    "first_name": "Mildred",
    "last_name": "Shaw",
    "favorite_color": "Teal"
}, {
    "first_name": "Kathryn",
    "last_name": "Miller",
    "favorite_color": "Teal"
}, {
    "first_name": "Kathryn",
    "last_name": "Hernandez",
    "favorite_color": "Pink"
}, {
    "first_name": "Shirley",
    "last_name": "Green",
    "favorite_color": "Fuscia"
}, {
    "first_name": "Jane",
    "last_name": "Fisher",
    "favorite_color": "Pink"
}, {
    "first_name": "Edward",
    "last_name": "Elliott",
    "favorite_color": "Maroon"
}, {
    "first_name": "Gloria",
    "last_name": "Bishop",
    "favorite_color": "Blue"
}, {
    "first_name": "Phyllis",
    "last_name": "Grant",
    "favorite_color": "Indigo"
}, {
    "first_name": "Theresa",
    "last_name": "Williams",
    "favorite_color": "Pink"
}];